### ISSUE TITLE
Add support for the GDC

### ISSUE THREAD

**Issue by konohitowa** [konohitowa/catebot#24]

**Comment by briannaboyce** [comment]
Kamino cloned this issue to briannaboyce/catebot

**Comment by konohitowa** [comment]
The GDC is [General Directory for Catechesis](http://www.vatican.va/roman_curia/congregations/cclergy/documents/rc_con_ccatheduc_doc_17041998_directory-for-catechesis_en.html) . As this is a Vatican document, closing as duplicate.

Duplicate of #25
