### ISSUE TITLE
CCC paragraph links just go to start of online CCC

### ISSUE THREAD

**Issue by deaconpat** [konohitowa/catebot#35]
Paragraph links provided in response to text that exceeds the 8000 character limit do not lead to the actual paragraph but rather just to the cover page of an online version of the CCC. The links could at least go the the page the paragraph(s) are on.

**Comment by konohitowa** [comment]
All of the links do that since USCCB changed their website to longer support linking into it as it had been previously. Requires a full reparsing of a suitable source (preferably not @ USCCB) and update of the database.

**Comment by briannaboyce** [comment]
Kamino cloned this issue to briannaboyce/catebot
