### ISSUE TITLE
Footer renders Improperly on "New Reddit"

### ISSUE THREAD

**Issue by konohitowa** [konohitowa/catebot#47]
The footer relies on non-breaking spaces for continuity in the superscript. New Reddit doesn't render these the same way so it looks all jacked up ([for example](https://new.reddit.com/r/Catholicism/comments/9ppja9/if_im_noncatholicnonchristian_will_i_go_to_hell/e83p5m0/?context=0)).

Change the footer to put parenthesis around the entire footer with a single carat (\^) at the start.

**Comment by Nokeo08** [comment]
I had this same issue on my bot. It is solved by putting what you want super scripted inside parents. 

Here is a link to where my bot assembles the footer of you want a reference. 

https://github.com/Nokeo08/standardsbot/blob/master/code/ResponseBuilder.py
